---
url: 	       INSERT_DOMAIN_HERE
future:      true
lsi:         false
#pygments:    true
markdown:    kramdown
permalink:   pretty

root:        /
source:      source
destination: public
plugins:     plugins
pygments:    false # default python pygments have been replaced by pygments.rb

description: ""
keywords: ""